#!/bin/sh
if ! [ -f u-boot.bin.sd.bin ]; then
  echo "ERROR: u-boot.bin.sd.bin not found - run make build"
  exit 1
fi
if [ $# -ne 1 ]; then
  echo "ERROR: Usage $0 /dev/sdX"
  exit 1
fi
SDDEV=$1
if ! [ -b "$SDDEV" ]; then
  echo "ERROR: $SDDEV is not a block device"
fi
echo "Writing bootloader to $SDDEV"
sudo dd conv=fsync,notrunc bs=512 seek=1 if=u-boot.bin.sd.bin of=$SDDEV
sudo sync
